export const SHOW_FIELD_TO_INSERT_PAYMENT = 'new-event-form/SHOW_FIELD_TO_INSERT_PAYMENT'
export const HIDE_FIELD_TO_INSERT_PAYMENT = 'new-event-form/HIDE_FIELD_TO_INSERT_PAYMENT'
export const SET_IMG_SOURCE = 'new-event-form/SET_IMG_SOURCE'
export const GET_COORDINATES_ON_CLICK = 'new-event-form/GET_COORDINATES_ON_CLICK'
export const ADD_NEW_EVENT_START = 'new-event-form/ADD_NEW_EVENT_START'
export const ADD_NEW_EVENT_END = 'new-event-form/ADD_NEW_EVENT_END'