export const ADD_EVENT_TO_FAVOURITES = 'list-events/MARK_EVENT_AS_FAVOURITES'
export const DELETE_EVENT_FROM_FAVOURITES = 'list-events/DELETE_EVENT_FROM_FAVOURITES'
export const ACTIVATE_FILTER = 'list-events/ACTIVATE_FILTER'